package cs320;

import java.util.Scanner;

// Requirements - Build portion of application where user can request the average temperature for a day of the week.
// Requirements - Assume another developer is developing the code to generate the average temperatures.
// Requirements - When the user enters a day such as "Monday", assume it is the last occurrence of that day and not a previous one 
/*
 * Pseudo code:  
 *  Generate array of days 
 *  Generate array of Average temperatures for the user - expect this array to be generated by another source in the future.
 *  Get user input for requested day of the week
 *  Print temperature for day of the week requested
 *  if ("week" is requested) {
 *  Print each day of the week with it's corresponding Average Temperature
 *  }
 */

public class Main {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		//array of days of the week
		String[] days = {"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"};
		
		
		//array of average temperatures
		float[] avgTemps = {55.9f, 62.3f, 62.34f, 55.89f, 71.01f, 47.56f, 68.23f};
		
		//get user input for requested day of the week
		boolean realDay = false;
		
		//create variable if we want to do some grouping that is not week in the future and want to use a different word
		String groupIndicator = "Week";
		
		
		System.out.println("Welcome to the weather application.  Please enter a day of the week, in english, and we will display for you");
		System.out.println("the average temperature for that day of the last week.  Or you can enter " + groupIndicator + " and we will display for you");
		System.out.println("the entire past " + groupIndicator.toLowerCase() + "'s average temperatures by day.");
		System.out.println("Please enter your selection now.");
		
		Scanner scnr = new Scanner(System.in);
		String userInput = "";
		
		while (realDay == false) {
			
			userInput = scnr.next();
			scnr.nextLine();
			if (userInput.isEmpty()) {
				System.out.println("Input cannot be empty.  Please enter a day of the week or the word " + groupIndicator + " to make a selection");
				continue;
			}
			if (userInput.length() > 1) {
				userInput = userInput.substring(0,1).toUpperCase() + userInput.substring(1);
			} else {
				userInput = userInput.toUpperCase();
			}
			
			//verify that the user input matches something in the days array or "week"
			if (userInput.equals(groupIndicator)) {
				realDay = true;
				break;
			}
			
			for (String day : days) {
				if (day.equals(userInput)) {
					realDay = true;
					break;
				}
			}//end for (String day : days)
			if (realDay == true) {
				break;
			}
			
			//handle if user Input did not match week or values in array.
			System.out.println("I'm afriaid I don't recognize that input.  As a reminder, the available input options are:");
			for(String day: days) {
				System.out.println(day);
			}
			System.out.println(groupIndicator);
		};//end while (realDay == false)
		
		//output if user entered valid day of the week
		for (int i = 0; i < days.length; i++) {
			if (userInput.equals(days[i])) {
				System.out.println("On the last " + days[i] + " it was an average temperature of " + avgTemps[i] + " degrees.");
			}
		}//end for loop
		
		//output if user entered input indicating they want the whole week
		if (userInput.equals(groupIndicator)) {
			for( int i = 0; i < days.length; i++ ) {
				System.out.println(days[i] + " had an average temperature of " + avgTemps[i] + " degrees.");
			}
		}
		
	}//end main(String args)

}// end class
